const key = "c7dc2200f66725961863fb901fd1e553";
const apiLink = "https://api.openweathermap.org/data/2.5/weather?";
const iconLink = "http://openweathermap.org/img/w/";

// List of verbose directions
const directions = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"];

// Mock weather data
const mockData = {"coord":{"lon":-0.13,"lat":51.51},
  "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"02n"}],
  "base":"stations",
  "main":{"temp":273.92,"pressure":1028,"humidity":74,"temp_min":273.15,"temp_max":275.15},
  "visibility":10000,"wind":{"speed":3.6,"deg":60},"clouds":{"all":8},"dt":1517808000,
  "sys":{"type":1,"id":5091,"message":0.0048,"country":"GB","sunrise":1517815931,
  "sunset":1517849855},"id":2643743,"name":"London","cod":200};

// ids of elements
const ids = {
  temperatureId: "temperature",
  temperatureUnitsId: "temperature-units",
  tempMinId: "temp-min",
  tempMinUnitsId: "temp-min-units",
  tempMaxId: "temp-max",
  tempMaxUnitsId: "temp-max-units",
  locationId: "location",
  iconId: "icon",
  descriptionId: "description",
  humidityId: "humidity",
  velocityId: "velocity",
  velocityUnitsId: "velocity-units",
  directionId: "direction",
  cityListId: "list-of-cities"
};

// List of cities
const cities = [
  "Kyiv",
  "Alchevsk",
  "Antratsyt",
  "Artemivsk",
  "Berdiansk",
  "Berdychiv",
  "Bila Tserkva",
  "Bilhorod-Dnistrovskyi",
  "Boryslav",
  "Boryspil",
  "Brianka",
  "Brovary",
  "Cherkasy",
  "Chernihiv",
  "Chernivtsi",
  "Chervonohrad",
  "Dniprodzerzhynsk",
  "Dnipropetrovsk",
  "Donetsk",
  "Drohobych",
  "Druzhkivka",
  "Dubno",
  "Dymytrov",
  "Dzerzhynsk",
  "Dzhankoy",
  "Enerhodar",
  "Evpatoria",
  "Fastiv",
  "Feodosia",
  "Horlivka",
  "Illichivsk",
  "Inhulets",
  "Ivano-Frankivsk",
  "Izium",
  "Izmail",
  "Kakhovka",
  "Kalush",
  "Kamianets-Podilskyi",
  "Kerch",
  "Kharkiv",
  "Khartsyzk",
  "Kherson",
  "Khmelnytskyi",
  "Kirovohrad",
  "Kolomyia",
  "Komsomolsk",
  "Konotop",
  "Korosten",
  "Kostiantynivka",
  "Kotovsk",
  "Kovel",
  "Kramatorsk",
  "Krasnoarmiysk",
  "Krasnodon",
  "Krasnyi Luch",
  "Kremenchuk",
  "Kryvyi Rih",
  "Kuznetsovsk",
  "Lozova",
  "Lubny",
  "Luhansk",
  "Lutsk",
  "Lviv",
  "Lysychansk",
  "Makiivka",
  "Marhanets",
  "Mariupol",
  "Melitopol",
  "Mukachevo",
  "Mykolaiv",
  "Myrhorod",
  "Nikopol",
  "Nizhyn",
  "Nova Kakhovka",
  "Novohrad-Volynskyi",
  "Novomoskovsk",
  "Novovolynsk",
  "Odesa",
  "Okhtyrka",
  "Oleksandriia",
  "Ordzhonikidze",
  "Pavlohrad",
  "Pervomaisk",
  "Pervomaisk",
  "Poltava",
  "Pryluky",
  "Rivne",
  "Romny",
  "Rovenky",
  "Rubizhne",
  "Sambir",
  "Sevastopol",
  "Severodonetsk",
  "Shakhtarsk",
  "Shepetivka",
  "Shostka",
  "Simferopol",
  "Sloviansk",
  "Smila",
  "Snizhne",
  "Stakhanov",
  "Stryi",
  "Sumy",
  "Sverdlovsk",
  "Svitlovodsk",
  "Ternopil",
  "Tokmak",
  "Torez",
  "Uman",
  "Uzhhorod",
  "Vinnytsia",
  "Volodymyr-Volynskyi",
  "Voznesensk",
  "Yalta",
  "Yenakiieve",
  "Yuzhnoukrainsk",
  "Zaporizhzhya",
  "Zhmerynka",
  "Zhovti Vody",
  "Zhytomyr"
];