const key = "c7dc2200f66725961863fb901fd1e553";
const apiLink = "https://api.openweathermap.org/data/2.5/weather?";
const iconLink = "http://openweathermap.org/img/w/";

// List of verbose directions
const directions = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"];

// List of cities
const cities = [
  "Kyiv",
  "Alchevsk",
  "Antratsyt",
  "Artemivsk",
  "Berdiansk",
  "Berdychiv",
  "Bila Tserkva",
  "Bilhorod-Dnistrovskyi",
  "Boryslav",
  "Boryspil",
  "Brianka",
  "Brovary",
  "Cherkasy",
  "Chernihiv",
  "Chernivtsi",
  "Chervonohrad",
  "Dniprodzerzhynsk",
  "Dnipropetrovsk",
  "Donetsk",
  "Drohobych",
  "Druzhkivka",
  "Dubno",
  "Dymytrov",
  "Dzerzhynsk",
  "Dzhankoy",
  "Enerhodar",
  "Evpatoria",
  "Fastiv",
  "Feodosia",
  "Horlivka",
  "Illichivsk",
  "Inhulets",
  "Ivano-Frankivsk",
  "Izium",
  "Izmail",
  "Kakhovka",
  "Kalush",
  "Kamianets-Podilskyi",
  "Kerch",
  "Kharkiv",
  "Khartsyzk",
  "Kherson",
  "Khmelnytskyi",
  "Kirovohrad",
  "Kolomyia",
  "Komsomolsk",
  "Konotop",
  "Korosten",
  "Kostiantynivka",
  "Kotovsk",
  "Kovel",
  "Kramatorsk",
  "Krasnoarmiysk",
  "Krasnodon",
  "Krasnyi Luch",
  "Kremenchuk",
  "Kryvyi Rih",
  "Kuznetsovsk",
  "Lozova",
  "Lubny",
  "Luhansk",
  "Lutsk",
  "Lviv",
  "Lysychansk",
  "Makiivka",
  "Marhanets",
  "Mariupol",
  "Melitopol",
  "Mukachevo",
  "Mykolaiv",
  "Myrhorod",
  "Nikopol",
  "Nizhyn",
  "Nova Kakhovka",
  "Novohrad-Volynskyi",
  "Novomoskovsk",
  "Novovolynsk",
  "Odesa",
  "Okhtyrka",
  "Oleksandriia",
  "Ordzhonikidze",
  "Pavlohrad",
  "Pervomaisk",
  "Pervomaisk",
  "Poltava",
  "Pryluky",
  "Rivne",
  "Romny",
  "Rovenky",
  "Rubizhne",
  "Sambir",
  "Sevastopol",
  "Severodonetsk",
  "Shakhtarsk",
  "Shepetivka",
  "Shostka",
  "Simferopol",
  "Sloviansk",
  "Smila",
  "Snizhne",
  "Stakhanov",
  "Stryi",
  "Sumy",
  "Sverdlovsk",
  "Svitlovodsk",
  "Ternopil",
  "Tokmak",
  "Torez",
  "Uman",
  "Uzhhorod",
  "Vinnytsia",
  "Volodymyr-Volynskyi",
  "Voznesensk",
  "Yalta",
  "Yenakiieve",
  "Yuzhnoukrainsk",
  "Zaporizhzhya",
  "Zhmerynka",
  "Zhovti Vody",
  "Zhytomyr"
];